
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class CreateAnInventoryParameters {
    /**
    * Label: JSON body, type: textarea
    */
    String data

    static CreateAnInventoryParameters initParameters(StepParameters sp) {
        CreateAnInventoryParameters parameters = new CreateAnInventoryParameters()

        def data = sp.getRequiredParameter('data').value
        parameters.data = data

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: a1bfc5e938f23cae442922816240cc8e ===
