
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class LaunchAndWaitAJobTemplateParameters {
    /**
    * Label: Job Template id, type: entry
    */
    String id
    /**
    * Label: Job Template Parameters, type: textarea
    */
    String body
    /**
    * Label: Job Status polling interval, type: entry
    */
    String checkInterval

    static LaunchAndWaitAJobTemplateParameters initParameters(StepParameters sp) {
        LaunchAndWaitAJobTemplateParameters parameters = new LaunchAndWaitAJobTemplateParameters()

        def id = sp.getRequiredParameter('id').value
        parameters.id = id
        def body = sp.getParameter('body').value
        parameters.body = body
        def checkInterval = sp.getParameter('checkInterval').value
        parameters.checkInterval = checkInterval

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: ae329da1e53b6ea1f9cac13a3584746d ===
