
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class ListInventoriesParameters {

    static ListInventoriesParameters initParameters(StepParameters sp) {
        ListInventoriesParameters parameters = new ListInventoriesParameters()

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 392464babac8743a642d16e0bca3fcfb ===
