
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class ListJobTemplatesParameters {

    static ListJobTemplatesParameters initParameters(StepParameters sp) {
        ListJobTemplatesParameters parameters = new ListJobTemplatesParameters()

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 44d16e72d359f81688ccd166775221c9 ===
