
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class RetrieveAnInventoryParameters {
    /**
    * Label: Inventory id, type: entry
    */
    String id

    static RetrieveAnInventoryParameters initParameters(StepParameters sp) {
        RetrieveAnInventoryParameters parameters = new RetrieveAnInventoryParameters()

        def id = sp.getRequiredParameter('id').value
        parameters.id = id

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: c5210adf290b0b8a248064b14e5a0273 ===
